FROM node:20.12.0-alpine3.19

WORKDIR /usr/src/app

COPY package.json package-lock.json turbo.json tsconfig.json ./

COPY apps ./apps
COPY packages ./packages

# Set environment variables
ARG DATABASE_URL
ENV DATABASE_URL=$DATABASE_URL

# Update npm to the latest version
RUN npm install -g npm@latest

# Install dependencies
RUN npm install

# Generate Prisma client
RUN npm run db:generate

# Build only the user-app
RUN npm run build --filter=user-app

CMD ["npm", "run", "start-user-app"]
